version: "3"
services:
  hotel:
    image: abdulrahman00/hotel:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "2000:2000"
    volumes:
      - /app/node_modules
      - .:/app
